### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'as_tuple' error on startup

### ISSUE THREAD

**Issue by E4zily** [cmyui/gulag#135]
root@ubuntu-s-2vcpu-4gb-sfo3-01:~/gulag# ./main.py
[08:03:49PM] It is not recommended to run gulag as root, especially in production..
gulag v3.5.4 ran into an issue before starting up :(
Traceback (most recent call last):
  File "/root/gulag/./main.py", line 209, in <module>
    raise SystemExit(loop.run_until_complete(main()))
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/root/gulag/./main.py", line 126, in main
    await misc.utils.update_mysql_structure()
  File "/root/gulag/misc/utils.py", line 691, in update_mysql_structure
    if latest_ver == current_ver:
  File "/usr/local/lib/python3.9/dist-packages/cmyui/version.py", line 22, in __eq__
    return self.as_tuple == other.as_tuple
AttributeError: 'NoneType' object has no attribute 'as_tuple'

**Comment by MitzaBobitza** [comment]
try adding a row to the startups table with `insert into startups (ver_major, ver_minor, ver_micro, datetime) values (3,5,4, now());`

**Comment by E4zily** [comment]
where do i execute that? i tried in mysql and it returned this

mysql> insert into startups (ver_major, ver_minor, ver_micro, datetime) values (3,5,4, now());
ERROR 1146 (42S02): Table 'mysql.startups' doesn't exist

**Comment by gamerboy80** [comment]
> ERROR 1146 (42S02): Table 'mysql.startups' doesn't exist

you have to type `use (name of gulag db here);` before that

**Comment by E4zily** [comment]
ok thank you

**Comment by cmyui** [comment]
oh jeez this should probably get fixed properly though
