### ISSUE TITLE
multiple errors on startup

### ISSUE THREAD

**Issue by E4zily** [cmyui/gulag#136]
root@ubuntu-s-2vcpu-4gb-sfo3-01:~/gulag# root@ubuntu-s-2vcpu-4gb-sfo3-01:~/gulag# ./main.py
4392
[03:47:00PM] It is not recommended to run gulag as root, especially in production..
gulag v3.5.4 ran into an issue before starting up :(
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 503, in _connect
    await self._request_authentication()
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 785, in _request_authentication
    auth_packet = await self._read_packet()
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 593, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.9/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.9/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1698, "Access denied for user 'root'@'localhost'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/gulag/misc/context.py", line 31, in acquire_mysql_db_pool
    await db_pool.connect(config)
  File "/usr/local/lib/python3.9/dist-packages/cmyui/mysql.py", line 37, in connect
    self.pool = await aiomysql.create_pool(**config, autocommit=True)
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/pool.py", line 29, in _create_pool
    await pool._fill_free_pool(False)
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/pool.py", line 167, in _fill_free_pool
    conn = await connect(echo=self._echo, loop=self._loop,
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 75, in _connect
    await conn._connect()
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 521, in _connect
    raise OperationalError(2003,
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/gulag/./main.py", line 209, in <module>
    raise SystemExit(loop.run_until_complete(main()))
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/root/gulag/./main.py", line 121, in main
    async with (
  File "/usr/lib/python3.9/contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "/root/gulag/misc/context.py", line 34, in acquire_mysql_db_pool
    await db_pool.close()
  File "/usr/local/lib/python3.9/dist-packages/cmyui/mysql.py", line 41, in close
    self.pool.close()
AttributeError: 'NoneType' object has no attribute 'close'

**Comment by E4zily** [comment]
fixed, now getting the same error as in #135
